<?php

/**
 * @file
 *
 * This module allows for the inclusion of Emailmanager as the native
 * Drupal mail handler using the new Drupal mail system interface.
 *
 * The Emailmanager PHP5 library include must be available for this module
 * to work correctly.
 *
 * Credit to the phpmailer module on which this is heavily based.
 */

/**
 * Implementation of hook_menu().
 */
function emailmanager_menu() {
  $items['admin/config/system/emailmanager'] = array(
    'title' => t('Emailmanager'),
    'description' => 'Configure Emailmanager settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emailmanager_settings_form'),
    'access callback' => 'emailmanager_settings_access',
    'file' => 'emailmanager.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_permission().
 */
function emailmanager_permission() {
	return array(
			'administer emailmanager' => array(
				'title' => t('Administer Emailmanager'), 
				'description' => t('Perform administration tasks for Emailmanager.'),
			),
		);
}

/**
 * Extract address and optional display name of an e-mail address.
 *
 * @param $address
 *   A string containing one or more valid e-mail address(es) separated with
 *   commas.
 *
 * @return
 *   An array containing all found e-mail addresses split into mail and name.
 *
 * @see http://tools.ietf.org/html/rfc5322#section-3.4
 */
function emailmanager_parse_address($address) {
  $parsed = array();
  $regexp = "/^(.*) <([a-z0-9]+(?:[_\\.-][a-z0-9]+)*@(?:[a-z0-9]+(?:[\.-][a-z0-9]+)*)+\\.[a-z]{2,})>$/i";

  // Split multiple addresses and process each.
  foreach (explode(',', $address) as $email) {
    $email = trim($email);
    if (preg_match($regexp, $email, $matches)) {
      $parsed[] = array('mail' => $matches[2], 'name' => trim($matches[1], '"'));
    }
    else {
      $parsed[] = array('mail' => $email, 'name' => '');
    }
  }
  return $parsed;
}

/**
 * Allow access to Emailmanager settings form
 */
function emailmanager_settings_access() {
  return user_access('administer emailmanager');
}